# .github/workflows/norm.yaml

name: CI

on: [push, pull_request]

jobs:
  norm_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "norm job triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "Running norminette on all files"
      - uses: actions/checkout@main
        with:
          submodules: true 
      - name: Install norminette
        run: pip install norminette
      - name: Run norminette
        run: |
          norminette src/ | grep Error
          norminette src/ > /dev/null
          exit $?
  
  make-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "make-check job triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "Running make check"
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: Check make
        run: make
