# .github/workflows/norm.yaml

name: CI

on: [push, pull_request]

jobs:
  norm_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "norm job triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "Running norminette on all files"
      - uses: actions/checkout@main
      - uses: alexandregv/norminette-action@v3.5.53
        with:
          flags: '.'
  
  make-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "make-check job triggered by a ${{ github.event_name }} event by ${{ github.actor }}"
      - run: echo "Running make check"
      -  uses: actions/checkout@main
      -  run: make
